### PR TITLE
[BEAM-245] Add IT to CassandraIO

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jkff

**Comment by jkff** [comment]
Thanks, can you clarify what is the path from having this PR, to having this integration test running continuously and automatically against existing Beam infrastructure? I'm not yet very familiar with our IT infra, but I'm assuming you are.

E.g. I see that for JdbcIO we have some Kubernetes scripts... though I don't see similar scripts for Elasticsearch; and even for JDBC I'm not quite sure where the Kubernetes cluster is located and how exactly it was set up to have a Postgres instance and so on, and whether it's practical to do the same for Cassandra.

**Comment by jbonofre** [comment]
As far as I know, the infrastructure part of the IT is managed by Jason and Stephen. The IT just provides some "samples" (kubernetes scripts, docker-compose scripts or simple shell scripts). The responsibility of the IT is:
1. to provide the options used by the infrastructure to locate the resources location (here, it's the Cassandra server host name and port)
2. to provide the test data set and a way to load it
3. to provide the actual test based on the data set, assuming the expected resources are available (provided by Jason & Stephen).

**Comment by jbonofre** [comment]
What do you think about moving this to Apache github PR ?

**Pull request closed without merging**
