### PR TITLE
[BEAM-214] ParquetIO

### PR DESCRIPTION
**Pull request by lgajowy**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lgajowy** [comment]
@jbonofre Hi JB! I played around a little bit with the recent parquet release and I think I managed to do a basic write using FileIO sink. This still need further development but I shought it's good to share it with you. Feel free to use this in your contribution if you find this valuable.  :)

**Comment by lgajowy** [comment]
Sorry for the mess in this PR - I rebased your commits ealier to use the latest master branch and fixed the gradle build. if you find this redundant feel free to just cherrypick the commits.

**Comment by jkff** [comment]
It seems difficult to find the particular ParquetIO commit here due to the difference in base; maybe just send a PR to apache/beam?

**Comment by lgajowy** [comment]
Yes, you're right - it came out even messier than i expected (35 participants in this pr). Sorry for that, closing.

**Pull request closed without merging**
